// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// BuildInfo build info
// swagger:model buildInfo
type BuildInfo struct {

	// build date
	// Required: true
	BuildDate *string `json:"buildDate"`

	// git branch
	// Required: true
	GitBranch *string `json:"gitBranch"`

	// git commit
	// Required: true
	GitCommit *string `json:"gitCommit"`

	// git state
	// Required: true
	GitState *string `json:"gitState"`

	// git summary
	// Required: true
	GitSummary *string `json:"gitSummary"`
}
