// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostMovieHandlerFunc turns a function with the right signature into a post movie handler
type PostMovieHandlerFunc func(PostMovieParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMovieHandlerFunc) Handle(params PostMovieParams) middleware.Responder {
	return fn(params)
}

// PostMovieHandler interface for that can handle valid post movie params
type PostMovieHandler interface {
	Handle(PostMovieParams) middleware.Responder
}

// NewPostMovie creates a new http.Handler for the post movie operation
func NewPostMovie(ctx *middleware.Context, handler PostMovieHandler) *PostMovie {
	return &PostMovie{Context: ctx, Handler: handler}
}

/*PostMovie swagger:route POST /api/movies movies postMovie

PostMovie post movie API

*/
type PostMovie struct {
	Context *middleware.Context
	Handler PostMovieHandler
}

func (o *PostMovie) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMovieParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
