// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Healthz healthz
// swagger:model healthz
type Healthz struct {

	// build info
	// Required: true
	BuildInfo *BuildInfo `json:"buildInfo"`
}

// Validate validates this healthz
func (m *Healthz) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuildInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Healthz) validateBuildInfo(formats strfmt.Registry) error {

	if err := validate.Required("buildInfo", "body", m.BuildInfo); err != nil {
		return err
	}

	if m.BuildInfo != nil {
		if err := m.BuildInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buildInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Healthz) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Healthz) UnmarshalBinary(b []byte) error {
	var res Healthz
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
